site_name: Sequrity API
site_url: https://sequrity-ai.github.io/sequrity-api/
site_description: A Python client for Sequrity API
repo_url: https://github.com/sequrity-ai/sequrity-api
repo_name: sequrity-ai/sequrity-api

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.footnote.tooltips

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            members_order: source
            show_signature_annotations: true
            separate_signature: true
            extensions:
              - griffe_pydantic:
                  schema: true
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Control:
          - Sending your first message: control/getting_started/first_message.md
          - Secure Tool Use with Dual-LLM: control/getting_started/tool_use_dual_llm.md
  - Learn:
      - Control:
          - control/learn/index.md
          - "Single vs. Dual-LLM": control/learn/single-vs-dual-llm.md
          - "Policy Language: sqrt-lite": control/learn/sqrt-lite.md
          - Compile and Execute LangGraph: control/learn/langgraph.md
  - Reference:
      - Control:
          - control/reference/index.md
          - SQRT-Lite DSL:
              - control/reference/dsl-lite/index.md
              - Grammar: control/reference/dsl-lite/grammar.md
          - REST API:
              - control/reference/rest_api/index.md
              - Chat Completion: control/reference/rest_api/chat_completion.md
              - Custom Headers:
                  - Bearer Token, X-Api-Key and X-Session-Id: control/reference/rest_api/api_key_session_id.md
                  - X-Security-Features: control/reference/rest_api/security_features.md
                  - X-Security-Policy: control/reference/rest_api/security_policy.md
                  - X-Security-Config: control/reference/rest_api/security_config.md
          - SequrityClient:
              - general/sequrity_client.md
              - SequrityClient.control:
                  - control/reference/sequrity_client/index.md
                  - Chat Completion: control/reference/sequrity_client/chat_completion.md
                  - LangGraph: control/reference/sequrity_client/langgraph.md
                  - Headers:
                      - FeaturesHeader: control/reference/sequrity_client/headers/features_header.md
                      - PolicyHeader: control/reference/sequrity_client/headers/policy_header.md
                      - ConfigHeader: control/reference/sequrity_client/headers/config_header.md
                  - ValueWithMeta: control/reference/sequrity_client/value_with_meta.md
              - service_provider: general/service_provider.md
  - Examples:
      - Control:
          - control/examples/index.md
          - Example-2026-01-22: control/examples/control-release-examples.ipynb
