[project]
    name="sequrity-api"
    version="0.0.1"
    description="Add your description here"
    readme="README.md"
    authors=[{ name="Cheng Zhang", email="chengzhang98@outlook.com" }]
    requires-python=">=3.13"
    dependencies=["httpx>=0.28.1", "pydantic>=2.11.9"]

[build-system]
    requires=["uv_build>=0.8.11,<0.9.0"]
    build-backend="uv_build"

[dependency-groups]
    dev=["openai>=1.107.3"]
